version: '3'
services:
# APP
  app:
    container_name: app
    build: ./app
    ports: 
      - 8080:8080 
    restart: on-failure
    environment:
      - APP_POSTGRES_HOST=postgres
    volumes:
      - api:/usr/src/app/
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - net
    links:
      - "postgres"
# POSTGRES
  postgres:
    build: ./db
    container_name: db
    restart: always
    user: postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - net

volumes:
  api:
  database_postgres:
networks:
  net:
    driver: bridge
